name: Deploy Infrastructure
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read    # For checkout

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Deploy with Pulumi
      uses: pulumi/actions@v4
      with:
        command: up
        stack-name: dev
        pulumi-version: 3.157.0
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        PULUMI_ESC_ENVIRONMENT: lab8test/dev  # ESC environment name
