name: Deploy infrastructure

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::664561225373:role/oidclab8
        aws-region: us-east-1
        role-session-name: GitHubActionsSession
        audience: sts.amazonaws.com

    - name: Install dependencies
      run: npm install

    - name: Deploy with Pulumi
      uses: pulumi/actions@v4
      with:
        command: up
        stack-name: dev
        pulumi-version: 3.157.0
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        AWS_REGION: us-east-1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEBUG: "true"
